png("plot3.png",width = 480, height = 480)
plot(dates,data[,7], ylab = "Energy sub metering", type = "l", xlab = "", col = "black")
lines(dates,data[,8], type = "l", col = "red")
lines(dates,data[,9], type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), lty = 1)
dev.off()